### PR TITLE
Fix postmortem debugging metadata for V8 7.2

### PR DESCRIPTION
**Pull request by cjihrig**
Fixes: https://github.com/nodejs/node-v8/issues/95

##### Checklist
- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by cjihrig** [comment]
The `deps` commit needs to be upstreamed.

**Comment by cjihrig** [comment]
V8 changes upstreamed at https://chromium-review.googlesource.com/c/v8/v8/+/1392449

**Comment by cjihrig** [comment]
The V8 patch landed. @targos is there anything left to do here?

**Comment by targos** [comment]
Pushed to `canary-base` in https://github.com/nodejs/node/commit/4ab8b42e26855b7295c09fd426d9398d607bc539. Thanks!

**Pull request closed without merging**
