### PR TITLE
obuild: update node.gyp to reference gypfiles/v8.gyp

### PR DESCRIPTION
**Pull request by joyeecheung**
Refs: https://github.com/v8/v8/commit/f9934aa9cf77b76c5fa78137e32939f30d9e2f81
Fixes: https://github.com/nodejs/node-v8/issues/36

Also noticed that `parallel/test-inspector-esm` currently fails because the scope chain and the format of the responses from the inspector have changed.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by hashseed** [comment]
LGTM.

Also note that I already fixed `parallel/test-inspector-esm` on [node/master](https://github.com/nodejs/node/commit/fa33f026cc2ce1bc1bb0e70399d8baaf794616f5).

**Comment by targos** [comment]
@joyeecheung thanks, I was working on it yesterday but couldn't finish. I am unable to compile though, here is the error I get (with V8 lkgr): 

```
...member /home/mzasso/git/nodejs/node-canary/out/Release/obj.target/v8_base/deps/v8/src/api.o in archive is not an object
collect2: error: ld returned 1 exit status
```

**Comment by targos** [comment]
```diff
diff --git a/Makefile b/Makefile
index f2ceb6e029..462fd283c9 100644
--- a/Makefile
+++ b/Makefile
@@ -96,7 +96,7 @@ $(NODE_G_EXE): config.gypi out/Makefile
 
 out/Makefile: common.gypi deps/uv/uv.gyp deps/http_parser/http_parser.gyp \
               deps/zlib/zlib.gyp deps/v8/gypfiles/toolchain.gypi \
-              deps/v8/gypfiles/features.gypi deps/v8/src/v8.gyp node.gyp \
+              deps/v8/gypfiles/features.gypi deps/v8/gypfiles/v8.gyp node.gyp \
               config.gypi
        $(PYTHON) tools/gyp_node.py -f make
 
diff --git a/node.gypi b/node.gypi
index bc9db9b814..f1029f2571 100644
--- a/node.gypi
+++ b/node.gypi
@@ -86,7 +86,7 @@
        target_arch=="ia32" or target_arch=="x32")', {
       'defines': [ 'NODE_ENABLE_VTUNE_PROFILING' ],
       'dependencies': [
-        'deps/v8/src/third_party/vtune/v8vtune.gyp:v8_vtune'
+        'deps/v8/gypfiles/v8vtune.gyp:v8_vtune'
       ],
     }],
     [ 'node_no_browser_globals=="true"', {
```

@joyeecheung I'm adding this diff to your commit and trying to run CI

**Comment by targos** [comment]
CI: https://ci.nodejs.org/job/node-test-commit-node-v8/286/

**Comment by targos** [comment]
Error on CI: `g++: error: /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x/out/Release/obj.target/deps/v8/src/libv8_base.a: No such file or directory`

**Comment by hashseed** [comment]
I think you also need to change the paths in `common.gypi` since `libv8_base.a` is no longer in `obj.target/deps/v8/src/`, but instead in `obj.target/deps/v8/gypfiles`.

**Comment by hashseed** [comment]
Err... that patch doesn't apply on your branch since it's for our vee-eight-lkgr.

**Comment by targos** [comment]
@hashseed thanks! new try: https://ci.nodejs.org/job/node-test-commit-node-v8/287/

**Comment by targos** [comment]
This is resolved!

**Pull request closed without merging**
