### PR TITLE
deps: update v8.gyp, run torque

### PR DESCRIPTION
**Pull request by bnoordhuis**
Teach v8.gyp to build and run torque, V8's DSL for generating builtins.

Fixes: #53

### CODE REVIEW

**Comment by bnoordhuis** [comment]
@targos Ping?

**Comment by targos** [comment]
Rubberstamp LGTM. Tested on Linux.

/cc @nodejs/gyp

**Comment by targos** [comment]
CI: https://ci.nodejs.org/job/node-test-pull-request/14474/

**Comment by targos** [comment]
Fails on s390x

```
08:29:15 /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x/out/Release/torque: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x/out/Release/torque)
```

**Comment by targos** [comment]
Fails on Windows:
```
..\third_party\antlr4\runtime\Cpp\runtime\src\tree\pattern\ParseTreePatternMatcher.cpp(113): error C2280: 'void std::rethrow_if_nested<antlr4::ParseCancellationException>(const _Ty &)': attempting to reference a deleted function [c:\workspace\node-compile-windows\deps\v8\gypfiles\torque.vcxproj]
          with
          [
              _Ty=antlr4::ParseCancellationException
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\exception(464): note: see declaration of 'std::rethrow_if_nested'
```

**Comment by mhdawson** [comment]
@jBarz my first guess is that we may be missing some setup in terms of the environment to be using the new compiler (the updated glibc) when running the tests.  Can you take a look at confirm if that is the case and if so what all we need to add to the setup script.

**Comment by jBarz** [comment]
gyp doesn't use the LDFLAGS environment variable to build `torque` which is a `host` side executable.
Instead it seems like we need to explictly set the variable when invoking `make`.

`make LDFLAGS.host="$LDFLAGS"`

**Comment by mhdawson** [comment]
Talked with @jBarz and we may resolve by setting the LD_LIBRARY_PATH in the build job.  Trying that out now.

**Comment by targos** [comment]
There is also another error on AIX:

```
../deps/v8/third_party/antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:302:16: error: stray '$' in program
       bool both$ = payload == EMPTY_RETURN_STATE && a_parent && b_parent;
                ^
../deps/v8/third_party/antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:305:15: error: stray '$' in program
       if (both$ || ax_ax) {
               ^
gmake[2]: *** [/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.host/torque/deps/v8/third_party/antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.o] Error 1
```

**Comment by mhdawson** [comment]
@john-yan @jBarz can you look at the AIX issue reported above.  Looks like a compiler error in v8 port.

**Comment by mhdawson** [comment]
CI run to test out linuxOne https://ci.nodejs.org/job/node-test-commit-linuxone/753/

**Comment by mhdawson** [comment]
Looks like @linuxOne is now ok.

**Comment by jBarz** [comment]
to fix aix

```diff
--- a/deps/v8/gypfiles/toolchain.gypi
+++ b/deps/v8/gypfiles/toolchain.gypi
@@ -1127,7 +1127,7 @@
             'ldflags': [ '-Wl,-bmaxdata:0x60000000/dsa' ],
           }],
           [ 'v8_target_arch=="ppc64"', {
-            'cflags': [ '-maix64' ],
+            'cflags': [ '-maix64', '-fdollars-in-identifiers' ],
             'ldflags': [ '-maix64 -Wl,-bbigtoc' ],
           }],
         ],
```

**Comment by mhdawson** [comment]
@jBarz I guess that change does not need to be upstreamed since v8 no longer uses gyp, but have we confirmed the equivalent is in the v8 repos when building with GN?

**Comment by vsemozhetbyt** [comment]
@nodejs/platform-windows, PTAL.
https://github.com/nodejs/node-v8/issues/53#issuecomment-385230856
https://github.com/nodejs/node-v8/pull/54#issuecomment-383941254

**Comment by targos** [comment]
I'm going to go ahead and cherry-pick this (with the aix fix) into the `canary-base` branch. We can investigate the Windows issue separately. It doesn't have to block all canary builds.

**Comment by targos** [comment]
Pushed to https://github.com/nodejs/node/commit/c83df641de33cac2b77ee9340974c86fb6b8ece2
Canay update: https://ci.nodejs.org/view/MyJobs/job/node-update-v8-canary/438/

**Comment by targos** [comment]
I'm going to open a new issue for the Windows error.
Thanks for the work, Ben!

**Pull request closed without merging**
