### PR TITLE
deps: update gen-postmortem jobs

### PR DESCRIPTION
**Pull request by cjihrig**
Fixes: https://github.com/nodejs/node-v8/issues/21

@targos can you give this a shot? If it works, I'll upstream it.

### CODE REVIEW

**Comment by targos** [comment]
Thanks. CI: https://ci.nodejs.org/job/node-test-commit-smartos/12592/

**Comment by cjihrig** [comment]
@targos is this good to upstream? Looks like the CI passed but the branch has conflicts.

**Comment by targos** [comment]
yes I suppose it's good

**Comment by cjihrig** [comment]
V8 CL: https://chromium-review.googlesource.com/c/v8/v8/+/741919

**Comment by targos** [comment]
The CL was merged. This can be closed. Thanks!

**Pull request closed without merging**
