### PR TITLE
test: update postmortem metadata test

### PR DESCRIPTION
**Pull request by cjihrig**
This commit updates the following postmortem metadata constants:

- `v8dbg_class_Map__inobject_properties_or_constructor_function_index__int`
  - This is now `v8dbg_class_Map__inobject_properties_start_or_constructor_function_index__char` as of https://github.com/v8/v8/commit/61bf2cc69217a4e9c7a40bb74269508fa26c2062
- `v8dbg_class_Map__instance_attributes__int`
  - This is now `v8dbg_class_Map__instance_type__uint16_t` as of https://github.com/v8/v8/commit/c00bb6da1cef9f7e9dab842904232255717f8291 and https://github.com/v8/v8/commit/cb46310a799eb0d60a613ead0af8c8200c5338b1
- `v8dbg_class_Map__instance_size__int`
  - This is now `v8dbg_class_Map__instance_size_in_words__char` as of https://github.com/v8/v8/commit/61bf2cc69217a4e9c7a40bb74269508fa26c2062
- `v8dbg_bit_field3_dictionary_map_shift`
  - This is now `v8dbg_bit_field3_is_dictionary_map_shift` as of https://github.com/v8/v8/commit/7a159da151e5f5437d6924de4fd142f854d3df4e

Fixes: https://github.com/nodejs/node-v8/issues/33

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by targos** [comment]
Thanks! Quick check: https://ci.nodejs.org/job/node-test-commit-light/41/

**Comment by cjihrig** [comment]
There was a failure in the CI, but unrelated.

**Comment by targos** [comment]
Thanks, landed in https://github.com/nodejs/node/commit/358a6287a1faf077a3118afd25c8e68d13e6e6a6 and https://github.com/nodejs/node/commit/034b64bcd32df404a9727583aa619319c5bccd4e.
I split the commit because some of the changes are needed for V8 6.4.

**Comment by cjihrig** [comment]
> Should we document the changes, say, in the Wiki?

I'm inclined to say no, simply because wikis get forgotten about and out of sync. I'm hoping to achieve the same thing in the commit log for the metadata test moving forward though.

**Pull request closed without merging**
