### PR TITLE
test: fix test-zlib-unused-weak on V8 8.2

### PR DESCRIPTION
**Pull request by mmarchini**
Ref: https://chromium-review.googlesource.com/c/v8/v8/+/1997438
Ref: https://chromium-review.googlesource.com/c/v8/v8/+/2010107
Ref: https://github.com/nodejs/node-v8/issues/144
Signed-off-by: Matheus Marchini <mmarchini@netflix.com>

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by targos** [comment]
Don't hesitate to push fixes to canary base. It's not easy to PR this repo because it's reset once a day by CI.

**Comment by targos** [comment]
And if we want to open pull requests, maybe we should do that against `canary-base` in the main repo? that branch is less likely to change every day.

**Comment by mmarchini** [comment]
Cherry-picked on `canary-base`.

> And if we want to open pull requests, maybe we should do that against canary-base in the main repo? that branch is less likely to change every day.

Agreed, it's probably better to open PRs there.

**Comment by mmarchini** [comment]
Yes, I sent the comment before pushing :sweat_smile:

Just waiting for `make test` to run after rebase+cherry pick, so I'll push in a few minutes.

**Comment by mmarchini** [comment]
nodejs/node@46b4399e49ba680fda6b9fbc1344eefb7bd0ae77

**Pull request closed without merging**
