### PR TITLE
Fix smartos build

### PR DESCRIPTION
**Pull request by cjihrig**
This should address #30

### CODE REVIEW

**Comment by targos** [comment]
Thanks! CI with my [6.4 branch](https://github.com/targos/node/commits/v8-6.4) including this commit: https://ci.nodejs.org/job/node-test-commit/14548/

**Comment by cjihrig** [comment]
Windows failed, but I don't think it's related. If you can confirm, I'll upstream this.

**Comment by targos** [comment]
I confirm it is not related. This is the Windows issue: https://github.com/nodejs/build/issues/1029

**Comment by cjihrig** [comment]
V8 CL: https://chromium-review.googlesource.com/c/v8/v8/+/806774

The changes in `src/v8abbr.h` would still need to land in Node though.

**Comment by targos** [comment]
Fix landed upstream: https://github.com/v8/v8/commit/c8ffe744b50caf260d6e417e34bb627edb42a971
I updated `v8abbr.h` in https://github.com/nodejs/node/commit/f4646655e3d27e95694063bee25ef6c91fff7cbb

**Pull request closed without merging**
