### PR TITLE
deps: update v8.gyp, fix torque on windows

### PR DESCRIPTION
**Pull request by bnoordhuis**
Turn on exceptions and RTTI, torque uses both.  They were already
enabled on UNIX platforms.

CI: https://ci.nodejs.org/job/node-test-pull-request/14616/

### CODE REVIEW

**Comment by targos** [comment]
@bnoordhuis is the second commit to fix "unresolved externals" errors?

**Comment by targos** [comment]
I just tested this on my Windows machine and it works. Are you going to upstream the change in torque's file?

**Comment by bnoordhuis** [comment]
Yes, I just need to get back to this.  Bit behind on schedule due to a back injury.

**Comment by refack** [comment]
Superseded by #61

**Pull request closed without merging**
