### PR TITLE
tools: update v8 gypfiles

### LINKED ISSUE #139: zlib build fail on windows platform
```console
C:\projects\appveyor-playground\node-v8\deps\v8\third_party\zlib\cpu_features.c(45,1): fatal error C1189: #error:  cpu_features.c CPU feature detection in not defined for your platform 
```

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix #139 

Thanks @seishun for point out the problem.

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by seishun** [comment]
That looks reasonable, although I think the proper long-term solution is to build V8 using GN.

**Comment by targos** [comment]
Thanks! Landed in https://github.com/nodejs/node/commit/50dd660fa88ff24217e77d57d94f4cee87e964f5

**Comment by gengjiawen** [comment]
> That looks reasonable, although I think the proper long-term solution is to build V8 using GN.

My first option would be cmake. GN would be much better if it's a standalone binary.


Also will the change land on this repo too ? @targos

**Comment by targos** [comment]
It's in now (there's a daily automatic update of this repo)

**Pull request closed without merging**
