### PR TITLE
v8: include right headers in torque output

### LINKED ISSUE #128: Build broken on Windows (VS2017)
https://ci.nodejs.org/job/node-compile-windows/30296/nodes=win-vs2017/console

```
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::FreeSpace': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\class-definitions-tq.h(107): note: see declaration of 'v8::internal::FreeSpace'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::FreeSpace
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(1224): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::FreeSpace,v8::internal::FreeSpace>' being compiled
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\x64\register-x64.h(153): note: see reference to class template instantiation 'v8::internal::RegisterBase<v8::internal::XMMRegister,16>' being compiled
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\x64\register-x64.h(53): note: see reference to class template instantiation 'v8::internal::RegisterBase<v8::internal::Register,16>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSRegExpStringIterator': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(59): note: see declaration of 'v8::internal::JSRegExpStringIterator'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSRegExpStringIterator
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(1566): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSRegExpStringIterator,v8::internal::JSRegExpStringIterator>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::SyntheticModule': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\heap\factory.h(66): note: see declaration of 'v8::internal::SyntheticModule'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::SyntheticModule
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(2460): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::SyntheticModule,v8::internal::SyntheticModule>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::TemplateObjectDescription': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\heap\factory.h(67): note: see declaration of 'v8::internal::TemplateObjectDescription'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::TemplateObjectDescription
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(2478): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::TemplateObjectDescription,v8::internal::TemplateObjectDescription>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSDateTimeFormat': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(53): note: see declaration of 'v8::internal::JSDateTimeFormat'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSDateTimeFormat
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3066): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSDateTimeFormat,v8::internal::JSDateTimeFormat>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSDisplayNames': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(54): note: see declaration of 'v8::internal::JSDisplayNames'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSDisplayNames
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3102): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSDisplayNames,v8::internal::JSDisplayNames>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSListFormat': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(55): note: see declaration of 'v8::internal::JSListFormat'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSListFormat
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3114): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSListFormat,v8::internal::JSListFormat>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSNumberFormat': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(57): note: see declaration of 'v8::internal::JSNumberFormat'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSNumberFormat
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3132): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSNumberFormat,v8::internal::JSNumberFormat>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSPluralRules': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(58): note: see declaration of 'v8::internal::JSPluralRules'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSPluralRules
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3162): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSPluralRules,v8::internal::JSPluralRules>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSRelativeTimeFormat': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(60): note: see declaration of 'v8::internal::JSRelativeTimeFormat'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSRelativeTimeFormat
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3186): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSRelativeTimeFormat,v8::internal::JSRelativeTimeFormat>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSLocale': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(56): note: see declaration of 'v8::internal::JSLocale'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSLocale
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3210): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSLocale,v8::internal::JSLocale>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSSegmenter': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(62): note: see declaration of 'v8::internal::JSSegmenter'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSSegmenter
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3216): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSSegmenter,v8::internal::JSSegmenter>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSSegmentIterator': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(61): note: see declaration of 'v8::internal::JSSegmentIterator'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSSegmentIterator
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3234): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSSegmentIterator,v8::internal::JSSegmentIterator>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSV8BreakIterator': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(63): note: see declaration of 'v8::internal::JSV8BreakIterator'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSV8BreakIterator
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3252): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSV8BreakIterator,v8::internal::JSV8BreakIterator>' being compiled
11:00:47 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::JSCollator': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\compiler\code-assembler.h(51): note: see declaration of 'v8::internal::JSCollator'
11:00:47   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(244): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
11:00:47           with
11:00:47           [
11:00:47               T=v8::internal::JSCollator
11:00:47           ]
11:00:47   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(3306): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::JSCollator,v8::internal::JSCollator>' being compiled
```

### PR DESCRIPTION
**Pull request by bnoordhuis**
I'm reasonably sure this fixes #128 but I can't test it right now because nodejs/node#30724 appears to have broken the Windows CI...
 
Fixes: #128

### CODE REVIEW

**Comment by bnoordhuis** [comment]
CI: https://ci.nodejs.org/job/node-test-commit-windows-fanned/32924/

So... it now compiles but fails with the following msbuild error:
```
13:13:49   v8_initializers.vcxproj -> ..\..\out\Release\lib\v8_initializers.lib
13:13:49 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2850,5): error MSB4018: The "AssignTargetPath" task failed unexpectedly. [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
13:13:49 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2850,5): error MSB4018: System.ArgumentException: Illegal characters in path. [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
```
(What illegal characters? Try and be helpful, msbuild...)
<hr>

The build generates a lot of warnings along these lines:
```
13:13:44 c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\deps\v8\third_party\v8\builtins\array-sort-tq-csa.cc(20757): warning C4506: no definition for inline function 'v8::internal::OrderedHashSet v8::internal::OrderedHashSet::cast(v8::internal::Object)' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
13:13:44 c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\deps\v8\third_party\v8\builtins\array-sort-tq-csa.cc(20757): warning C4506: no definition for inline function 'v8::internal::OrderedHashMap v8::internal::OrderedHashMap::cast(v8::internal::Object)' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
```
That's because of this line, the implementation probably should have been in the -inl.h file. 
https://github.com/nodejs/node-v8/blob/d345bf47b77e8a8605df3f5ba86b06c444bb45b7/deps/v8/src/objects/ordered-hash-table.h#L132

**Comment by bnoordhuis** [comment]
I put two build binlogs side-to-side (one of this PR and one of a successful build of nodejs/node) and I didn't see any glaring discrepancies. If there's an illegal file path in there somewhere it's not immediately obvious to me what it is.

**Comment by targos** [comment]
trying on my computer...

**Comment by targos** [comment]
Visual Studio doesn't give more information...

image

**Comment by targos** [comment]
@joaocgreis any idea on how we could debug further?

**Comment by targos** [comment]
@nodejs/platform-windows

**Comment by cclauss** [comment]
Please fix conflicts.

**Comment by bnoordhuis** [comment]
@cclauss Rebased.

**Comment by targos** [comment]
Rebased again to include https://github.com/nodejs/node-v8/pull/136.
New CI: https://ci.nodejs.org/job/node-test-commit-windows-fanned/33247/

**Comment by targos** [comment]
Error is now:

```
15:34:08 c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): error C2139: 'v8::internal::PropertyDescriptorObject': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
15:34:08   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\class-definitions-tq.h(162): note: see declaration of 'v8::internal::PropertyDescriptorObject'
15:34:08   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\tnode.h(250): note: see reference to class template instantiation 'std::is_convertible<T,v8::internal::Object>' being compiled
15:34:08           with
15:34:08           [
15:34:08               T=v8::internal::PropertyDescriptorObject
15:34:08           ]
15:34:08   c:\workspace\node-compile-windows\node\out\release\obj\global_intermediate\torque-output-root\torque-generated\exported-macros-assembler-tq.cc(2071): note: see reference to class template instantiation 'v8::internal::is_subtype<v8::internal::PropertyDescriptorObject,v8::internal::PropertyDescriptorObject>' being compiled
15:34:08   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\x64\register-x64.h(153): note: see reference to class template instantiation 'v8::internal::RegisterBase<v8::internal::XMMRegister,16>' being compiled
15:34:08   c:\workspace\node-compile-windows\node\deps\v8\src\codegen\x64\register-x64.h(53): note: see reference to class template instantiation 'v8::internal::RegisterBase<v8::internal::Register,16>' being compiled
15:34:37 
```

**Comment by joaocgreis** [comment]
It looks like the only thing missing here is `src/objects/property-descriptor-object.h`.

This fixes building for me: https://github.com/JaneaSystems/node/commit/e9f7149fd9210353f407ebafcf5c12df4dc48ffc

CI: https://ci.nodejs.org/view/All/job/node-test-commit-windows-fanned/33341/

**Comment by targos** [comment]
Nice, thanks!

@bnoordhuis would you like to upstream the changes?

**Comment by gengjiawen** [comment]
This need rebase.

**Comment by targos** [comment]
Landed in canary-base with https://github.com/nodejs/node-v8/pull/143

**Pull request closed without merging**
