### PR TITLE
build: fix build on msvc

### PR DESCRIPTION
**Pull request by gengjiawen**
If this works, I will port it to upstream v8.

### CODE REVIEW

**Comment by targos** [comment]
Thanks @gengjiawen. I pushed your commit to `canary-base`.

**Comment by gengjiawen** [comment]
Upstream has been merged, should we remove this commit?

**Comment by ryzokuken** [comment]
@gengjiawen I think it would be taken care of once your commit lands in LKGR and I'll remove the empty commit.

**Comment by targos** [comment]
image

The commit is in LKGR

**Comment by ryzokuken** [comment]
@targos then I guess we'll have a rebase error breaking the CI tomorrow and I'll fix this!

**Pull request closed without merging**
